### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by alexbishopbootcamp** [alexbishopbootcamp/music-lyric-player#17]
![Image](https://user-images.githubusercontent.com/132449305/254840167-c818053d-fe62-443c-8fe8-ad2d58f037b5.png)

![Image](https://user-images.githubusercontent.com/132449305/254839877-728e98a6-048d-46cc-89a8-414cc84518bc.png)

![Image](https://user-images.githubusercontent.com/132449305/254840322-2712f0ac-6719-45ac-97d7-35a2cc4c4978.png)

**Comment by alexbishopbootcamp** [comment]
These are all the different variations to the view I can think of. Some may require extra wireframes:

- First visit landing page with no search bar and a "Log in with Spotify button" (User can't do anything giving app access)
- ~~Landing page with search bar (authenticated)~~
- Landing page with search bar and search results shown under search bar
- Player page
- Player page with search results under search bar
- About page (Credits, Copyright and Attributions)

**Comment by trahy** [comment]
![Image](https://github.com/alexbishopbootcamp/music-lyric-player/assets/132577045/955ed444-35eb-4c8b-97a2-937e3ecfa6e2)



![Image](https://github.com/alexbishopbootcamp/music-lyric-player/assets/132577045/5e11a947-0a98-4a59-b2e6-cd42d0036e21)



![Image](https://github.com/alexbishopbootcamp/music-lyric-player/assets/132577045/4cc9d411-5ce3-4104-bed7-415e661f451d)
